module FDSSpec (fdsSpec) where

import qualified Data.Map.Strict as M
import Text.Namelist

fdsSpec :: NamelistSpec
fdsSpec = M.fromList
    [ ("HEAD", M.fromList
        [ ("CHID", PSString)
        , ("FYI", PSString)
        , ("TITLE", PSString)
        , ("STOPFDS", PSInt)
        ])
    , ("MESH", M.fromList
        [ ("COLOR", PSString)
        , ("CYLINDRICAL", PSBool)
        , ("EVACUATION", PSBool)
        , ("EVAC_HUMANS", PSBool)
        , ("EVAC_Z_OFFSET", PSString)
        , ("FYI", PSString)
        , ("ID", PSString)
        , ("IJK", PSArray PSInt)
        , ("LEVEL", PSInt)
        , ("MPI_PROCESS", PSInt)
        , ("MULT_ID", PSString)
        , ("RGB", PSArray PSDouble)
        , ("XB", PSArray PSDouble)
        , ("N_THREADS", PSInt)
        , ("PERIODIC_MESH_IDS", PSArray PSString)
        ])
    , ("TIME", M.fromList
        [ ("DT", PSDouble)
        , ("EVAC_DT_FLOWFIELD", PSDouble)
        , ("EVAC_DT_STEADY_STATE", PSDouble)
        , ("FYI", PSString)
        , ("LIMITING_DT_RATIO", PSDouble)
        , ("LOCK_TIME_STEP", PSBool)
        , ("RESTRICT_TIME_STEP", PSBool)
        , ("T_BEGIN", PSDouble)
        , ("T_END", PSDouble)
        , ("T_END_GEOM", PSDouble)
        , ("TIME_SHRINK_FACTOR", PSDouble)
        , ("WALL_INCREMENT", PSInt)
        , ("WALL_INCREMENT_HT3D", PSInt)
        , ("TWFIN", PSDouble)
        ])
    , ("CSVF", M.fromList
        [ ("CSVFILE", PSString)
        , ("UVWFILE", PSString)
        ])
    , ("MULT", M.fromList
        [ ("DX", PSDouble)
        , ("DXB", PSArray PSDouble)
        , ("DX0", PSDouble)
        , ("DY", PSDouble)
        , ("DY0", PSDouble)
        , ("DZ", PSDouble)
        , ("DZ0", PSDouble)
        , ("FYI", PSString)
        , ("ID", PSString)
        , ("I_LOWER", PSInt)
        , ("I_UPPER", PSInt)
        , ("J_LOWER", PSInt)
        , ("J_UPPER", PSInt)
        , ("K_LOWER", PSInt)
        , ("K_UPPER", PSInt)
        , ("N_LOWER", PSInt)
        , ("N_UPPER", PSInt)
        ])
    , ("MISC", M.fromList
        [ ("AGGLOMERATION", PSBool)
        , ("AEROSOL_AL2O3", PSBool)
        , ("ALLOW_SURFACE_PARTICLES", PSBool)
        , ("ALLOW_UNDERSIDE_PARTICLES", PSBool)
        , ("ASSUMED_GAS_TEMPERATURE", PSDouble)
        , ("ASSUMED_GAS_TEMPERATURE_RAMP", PSString)
        , ("BAROCLINIC", PSBool)
        , ("BNDF_DEFAULT", PSBool)
        , ("CC_IBM", PSBool)
        , ("CNF_CUTOFF", PSDouble)
        , ("CFL_MAX", PSDouble)
        , ("CFL_MIN", PSDouble)
        , ("CFL_VELOCITY_NORM", PSInt)
        , ("CHECK_HT", PSBool)
        , ("CHECK_REALIZABILITY", PSBool)
        , ("CHECK_VN", PSBool)
        , ("CLIP_MASS_FRACTION", PSBool)
        , ("COMPUTE_VISCOSITY_TWICE", PSBool)
        , ("COMPUTE_ZETA_SOURCE_TERM", PSBool)
        , ("CONSTANT_H_SOLID", PSBool)
        , ("CONSTANT_SPECIFIC_HEAT_RATIO", PSBool)
        , ("CORIOLIS_VECTOR", PSArray PSDouble)
        , ("CORRECT_SUBGRID_TEMPERATURE", PSBool)
        , ("COUPLED_1D3D_HEAT_TRANSFER", PSBool)
        , ("C_DEARDORFF", PSDouble)
        , ("C_RNG", PSDouble)
        , ("C_RNG_CUTOFF", PSDouble)
        , ("C_SMAGORINSKY", PSDouble)
        , ("C_VREMAN", PSDouble)
        , ("DNS", PSBool)
        , ("DRAG_CFL_MAX", PSDouble)
        , ("DT_MEAN_FORCING", PSDouble)
        , ("ENTHALPY_TRANSPORT", PSBool)
        , ("EVACUATION_DRILL", PSBool)
        , ("EVACUATION_MC_MODE", PSBool)
        , ("EVAC_PRESSURE_ITERATIONS", PSInt)
        , ("EVAC_SURF_DEFAULT", PSString)
        , ("EVAC_TIME_ITERATIONS", PSInt)
        , ("EVAPORATION", PSBool)
        -- , ("EXCHANGE_EDGES", PSString)
        , ("EXTERNAL_BOUNDARY_CORRECTION", PSBool)
        , ("EXTINCTION_MODEL", PSString)
        , ("HVAC_PRES_RELAX", PSDouble)
        , ("HT3D_TEST", PSInt)
        , ("FDS5_OPTIONS", PSBool)
        , ("FLUX_LIMITER", PSInt)
        , ("FORCE_VECTOR", PSArray PSDouble)
        , ("FREEZE_VELOCITY", PSBool)
        , ("FYI", PSString)
        , ("GAMMA", PSDouble)
        , ("GRAVITATIONAL_DEPOSITION", PSBool)
        , ("GRAVITATIONAL_SETTLING", PSBool)
        , ("GROUND_LEVEL", PSDouble)
        , ("GVEC", PSArray PSDouble)
        , ("DT_HVAC", PSDouble)
        , ("H_F_REFERENCE_TEMPERATURE", PSDouble)
        , ("HRRPUV_MAX_SMV", PSDouble)
        , ("HUMIDITY", PSDouble)
        , ("HVAC_MASS_TRANSPORT", PSBool)
        , ("IBLANK_SMV", PSBool)
        , ("IMMERSED_BOUNDARY_METHOD", PSInt)
        , ("INITIAL_UNMIXED_FRACTION", PSDouble)
        -- , ("KINETIC_ENERGY_SOURCE", PSString)
        , ("LAPSE_RATE", PSDouble)
        , ("LES_FILTER_WIDTH", PSString)
        , ("MAX_CHEMISTRY_ITERATIONS", PSInt)
        , ("MAX_LEAK_PATHS", PSInt)
        , ("MAXIMUM_VISIBILITY", PSDouble)
        , ("MEAN_FORCING", PSArray PSBool)
        , ("MPI_TIMEOUT", PSDouble)
        , ("N_FIXED_CHEMISTRY_SUBSTEPS", PSInt)
        , ("NEAR_WALL_TURBULENCE_MODEL", PSString)
        -- , ("NEW_MOMENTUM_NUDGING", PSString)
        -- , ("NEW_OPEN_BOUNDARY", PSString)
        , ("NOISE", PSBool)
        , ("NOISE_VELOCITY", PSDouble)
        , ("NO_EVACUATION", PSBool)
        , ("NO_RAMPS", PSBool)
        -- , ("NORTHANGLE", PSString)
        , ("OVERWRITE", PSBool)
        , ("PARTICLE_CFL_MAX", PSDouble)
        , ("PARTICLE_CFL_MIN", PSDouble)
        , ("PARTICLE_CFL", PSBool)
        , ("PERIODIC_TEST", PSInt)
        -- , ("PROFILING", PSString)
        , ("POROUS_FLOOR", PSBool)
        -- , ("POTENTIAL_TEMPERATURE_CORRECTION", PSString)
        , ("PR", PSDouble)
        , ("PROCESS_ALL_MESHES", PSBool)
        , ("PROJECTION", PSBool)
        , ("P_INF", PSDouble)
        -- , ("RAMP_FVX_T", PSString)
        -- , ("RAMP_FVY_T", PSString)
        -- , ("RAMP_FVZ_T", PSString)
        , ("RAMP_GX", PSString)
        , ("RAMP_GY", PSString)
        , ("RAMP_GZ", PSString)
        , ("RAMP_U0", PSString)
        , ("RAMP_U0_T", PSString)
        , ("RAMP_V0", PSString)
        , ("RAMP_V0_T", PSString)
        , ("RAMP_W0", PSString)
        , ("RAMP_W0_T", PSString)
        , ("RAMP_U0_Z", PSString)
        , ("RAMP_V0_Z", PSString)
        , ("RAMP_W0_Z", PSString)
        -- , ("RADIATION", PSString)
        , ("RESEARCH_MODE", PSBool)
        , ("RESTART", PSBool)
        , ("RESTART_CHID", PSString)
        , ("RICHARDSON_ERROR_TOLERANCE", PSDouble)
        , ("RUN_AVG_FAC", PSDouble)
        , ("SC", PSDouble)
        , ("SECOND_ORDER_INTERPOLATED_BOUNDARY", PSBool)
        , ("SECOND_ORDER_PARTICLE_TRANSPORT", PSBool)
        , ("SHARED_FILE_SYSTEM", PSBool)
        -- , ("SLIP_CONDITION", PSString)
        , ("SMOKE_ALBEDO", PSDouble)
        , ("SOLID_PHASE_ONLY", PSBool)
        -- , ("SOOT_OXIDATION", PSString)
        -- , ("SPONGE_LAYER_DISTANCE", PSString)
        , ("STRATIFICATION", PSBool)
        , ("SUPPRESSION", PSBool)
        -- , ("SURF_DEFAULT", PSString)
        -- , ("TEMPERATURE_DEPENDENT_REACTION", PSString)
        -- , ("TENSOR_DIFFUSIVITY", PSString)
        , ("TERRAIN_CASE", PSBool)
        , ("TERRAIN_IMAGE", PSString)
        -- , ("TEST_FILTER_QUADRATURE", PSString)
        , ("TEXTURE_ORIGIN", PSArray PSDouble)
        , ("THERMOPHORETIC_DEPOSITION", PSBool)
        , ("THICKEN_OBSTRUCTIONS", PSBool)
        -- , ("TRANSPORT_UNMIXED_FRACTION", PSString)
        -- , ("TRANSPORT_ZETA_SCHEME", PSString)
        , ("TMPA", PSDouble)
        , ("TURBULENCE_MODEL", PSString)
        , ("TURBULENT_DEPOSITION", PSBool)
        -- , ("TURB_INIT_CLOCK", PSString)
        , ("U0", PSDouble)
        , ("UVW_FILE", PSString)
        , ("V0", PSDouble)
        , ("VEG_LEVEL_SET_COUPLED", PSBool)
        , ("VEG_LEVEL_SET_UNCOUPLED", PSBool)
        , ("VERBOSE", PSDouble)
        , ("VISIBILITY_FACTOR", PSDouble)
        , ("VN_MAX", PSDouble)
        , ("VN_MIN", PSDouble)
        , ("Y_CO2_INFTY", PSDouble)
        , ("Y_O2_INFTY", PSDouble)
        , ("W0", PSDouble)
        -- , ("WD_PROPS", PSString)
        -- , ("WIND_BOUNDARY", PSString)
        -- , ("WIND_ONLY", PSString)
        ])
    , ("DUMP", M.fromList
        [ ("CLIP_RESTART_FILES", PSBool)
        , ("COLUMN_DUMP_LIMIT", PSBool)
        , ("CTRL_COLUMN_LIMIT", PSInt)
        , ("DEVC_COLUMN_LIMIT", PSInt)
        , ("DT_BNDE", PSDouble)
        , ("DT_BNDF", PSDouble)
        , ("DT_CPU", PSDouble)
        , ("DT_CTRL", PSDouble)
        , ("DT_DEVC", PSDouble)
        , ("DT_DEVC_LINE", PSDouble)
        , ("DT_FLUSH", PSDouble)
        , ("DT_GEOM", PSDouble)
        , ("DT_HRR", PSDouble)
        , ("DT_ISOF", PSDouble)
        , ("DT_MASS", PSDouble)
        , ("DT_PART", PSDouble)
        , ("DT_PL3D", PSDouble)
        , ("DT_PROF", PSDouble)
        , ("DT_RESTART", PSDouble)
        , ("DT_SL3D", PSDouble)
        , ("DT_SLCF", PSDouble)
        , ("EB_PART_FILE", PSBool)
        , ("FLUSH_FILE_BUFFERS", PSBool)
        , ("GEOM_DIAG", PSBool)
        , ("MASS_FILE", PSBool)
        , ("MAXIMUM_PARTICLES", PSInt)
        , ("MMS_TIMER", PSDouble)
        , ("NFRAMES", PSInt)
        , ("PLOT3D_PART_ID", PSString)
        , ("PLOT3D_QUANTITY", PSArray PSString)
        , ("PLOT3D_SPEC_ID", PSString)
        , ("PLOT3D_VELO_INDEX", PSInt)
        , ("RENDER_FILE", PSString)
        , ("SIG_FIGS", PSInt)
        , ("SIG_FIGS_EXP", PSInt)
        , ("SMOKE3D", PSBool)
        , ("SMOKE3D_QUANTITY", PSString)
        , ("SMOKE3D_SPEC_ID", PSString)
        , ("STATUS_FILES", PSBool)
        , ("SUPPRESS_DIAGNOSTICS", PSBool)
        , ("UVW_TIMER", PSArray PSDouble)
        , ("VELOCITY_ERROR_FILE", PSBool)
        , ("WRITE_XYZ", PSBool)
        ])
    , ("SPEC", M.fromList
        [ ("AEROSOL", PSBool)
        , ("ALIAS", PSString)
        , ("BACKGROUND", PSBool)
        -- , ("COPY_LUMPED", PSString)
        , ("CONDUCTIVITY", PSDouble)
        , ("CONDUCTIVITY_SOLID", PSDouble)
        , ("DENSITY_LIQUID", PSDouble)
        , ("DENSITY_SOLID", PSDouble)
        , ("DIFFUSIVITY", PSDouble)
        , ("ENTHALPY_OF_FORMATION", PSDouble)
        , ("EPSILONKLJ", PSDouble)
        , ("FIC_CONCENTRATION", PSDouble)
        , ("FLD_LETHAL_DOSE", PSDouble)
        , ("FORMULA", PSString)
        , ("FYI", PSString)
        , ("HEAT_OF_VAPORIZATION", PSDouble)
        , ("H_V_REFERENCE_TEMPERATURE", PSDouble)
        , ("ID", PSString)
        , ("LUMPED_COMPONENT_ONLY", PSBool)
        , ("MASS_EXTINCTION_COEFFICIENT", PSDouble)
        , ("MASS_FRACTION", PSArray PSDouble)
        , ("MASS_FRACTION_0", PSDouble)
        -- , ("MAX_DIAMETER", PSString)
        , ("MEAN_DIAMETER", PSDouble)
        , ("MELTING_TEMPERATURE", PSDouble)
        -- , ("MIN_DIAMETER", PSString)
        , ("MW", PSDouble)
        -- , ("N_BINS", PSString)
        , ("PR_GAS", PSDouble)
        , ("PRIMITIVE", PSBool)
        , ("RADCAL_ID", PSString)
        , ("RAMP_CP", PSString)
        , ("RAMP_CP_L", PSString)
        , ("RAMP_D", PSString)
        , ("RAMP_G_F", PSString)
        , ("RAMP_K", PSString)
        , ("RAMP_MU", PSString)
        , ("REFERENCE_ENTHALPY", PSDouble)
        , ("REFERENCE_TEMPERATURE", PSDouble)
        , ("SIGMALJ", PSDouble)
        , ("SPEC_ID", PSArray PSString)
        , ("SPECIFIC_HEAT", PSDouble)
        , ("SPECIFIC_HEAT_LIQUID", PSDouble)
        , ("VAPORIZATION_TEMPERATURE", PSDouble)
        , ("VISCOSITY", PSDouble)
        , ("VOLUME_FRACTION", PSArray PSDouble)
        ])
    , ("REAC", M.fromList
        [ ("A", PSDouble)
        -- , ("ALT_REAC_ID", PSString)
        , ("AUTO_IGNITION_TEMPERATURE", PSDouble)
        , ("C", PSDouble)
        , ("CHECK_ATOM_BALANCE", PSBool)
        , ("CO_YIELD", PSDouble)
        , ("CRITICAL_FLAME_TEMPERATURE", PSDouble)
        , ("E", PSDouble)
        , ("EPUMO2", PSDouble)
        -- , ("K", PSString)
        , ("EQUATION", PSString)
        , ("FIXED_MIX_TIME", PSDouble)
        -- , ("FLAME_SPEED", PSString)
        -- , ("FLAME_SPEED_EXPONENT", PSString)
        -- , ("FLAME_SPEED_TEMPERATURE", PSString)
        , ("FORMULA", PSString)
        , ("FUEL", PSString)
        , ("FUEL_RADCAL_ID", PSString)
        -- , ("FWD_ID", PSString)
        , ("FYI", PSString)
        , ("H", PSDouble)
        , ("HEAT_OF_COMBUSTION", PSDouble)
        , ("ID", PSString)
        , ("IDEAL", PSBool)
        , ("N", PSDouble)
        , ("NU", PSArray PSDouble)
        , ("N_S", PSArray PSDouble)
        , ("N_T", PSDouble)
        , ("O", PSDouble)
        -- , ("ODE_SOLVER", PSString)
        , ("RADIATIVE_FRACTION", PSDouble)
        , ("RAMP_CHI_R", PSString)
        -- , ("RAMP_FS", PSString)
        , ("REAC_ATOM_ERROR", PSDouble)
        , ("REAC_MASS_ERROR", PSDouble)
        -- , ("REVERSE", PSString)
        , ("SOOT_H_FRACTION", PSDouble)
        , ("SOOT_YIELD", PSDouble)
        , ("SPEC_ID_N_S", PSArray PSString)
        , ("SPEC_ID_NU", PSArray PSString)
        -- , ("TABLE_FS", PSString)
        -- , ("TAU_CHEM", PSString)
        -- , ("TAU_FLAME", PSString)
        , ("THIRD_BODY", PSBool)
        -- , ("TURBULENT_FLAME_SPEED_ALPHA", PSString)
        -- , ("TURBULENT_FLAME_SPEED_EXPONENT", PSString)
        -- , ("Y_P_MIN_EDC", PSString)
        ])
    , ("PART", M.fromList
        [ ("AGE", PSDouble)
        , ("BREAKUP", PSBool)
        , ("BREAKUP_CNF_RAMP_ID", PSString)
        , ("BREAKUP_DISTRIBUTION", PSString)
        , ("BREAKUP_GAMMA_D", PSDouble)
        , ("BREAKUP_RATIO", PSDouble)
        , ("BREAKUP_SIGMA_D", PSDouble)
        , ("CHECK_DISTRIBUTION", PSBool)
        , ("CNF_RAMP_ID", PSString)
        , ("COLOR", PSString)
        , ("COMPLEX_REFRACTIVE_INDEX", PSDouble)
        , ("CTRL_ID", PSString)
        , ("DENSE_VOLUME_FRACTION", PSDouble)
        , ("DEVC_ID", PSString)
        , ("DIAMETER", PSDouble)
        , ("DISTRIBUTION", PSString)
        , ("DRAG_COEFFICIENT", PSArray PSDouble)
        , ("DRAG_LAW", PSString)
        , ("FREE_AREA_FRACTION", PSDouble)
        , ("FYI", PSString)
        , ("GAMMA_D", PSDouble)
        , ("HEAT_OF_COMBUSTION", PSDouble)
        , ("HORIZONTAL_VELOCITY", PSDouble)
        , ("ID", PSString)
        , ("INITIAL_TEMPERATURE", PSDouble)
        , ("MASSLESS", PSBool)
        , ("MAXIMUM_DIAMETER", PSDouble)
        , ("MINIMUM_DIAMETER", PSDouble)
        , ("MONODISPERSE", PSBool)
        , ("N_STRATA", PSInt)
        , ("ORIENTATION", PSArray PSDouble)
        , ("PERMEABILITY", PSArray PSDouble)
        -- , ("PERIODIC_X", PSString)
        -- , ("PERIODIC_Y", PSString)
        -- , ("PERIODIC_Z", PSString)
        , ("POROUS_VOLUME_FRACTION", PSDouble)
        , ("PROP_ID", PSString)
        , ("QUANTITIES", PSArray PSString)
        , ("QUANTITIES_SPEC_ID", PSArray PSString)
        , ("RADIATIVE_PROPERTY_TABLE", PSString)
        , ("REAL_REFRACTIVE_INDEX", PSDouble)
        , ("RGB", PSArray PSDouble)
        , ("SAMPLING_FACTOR", PSInt)
        , ("SECOND_ORDER_PARTICLE_TRANSPORT", PSBool)
        , ("SIGMA_D", PSDouble)
        , ("SPEC_ID", PSString)
        , ("STATIC", PSBool)
        , ("SURFACE_TENSION", PSDouble)
        , ("SURF_ID", PSString)
        , ("TARGET_ONLY", PSBool)
        , ("TURBULENT_DISPERSION", PSBool)
        , ("VERTICAL_VELOCITY", PSDouble)
        ])
    , ("PROP", M.fromList
        [ ("ACTIVATION_OBSCURATION", PSDouble)
        , ("ACTIVATION_TEMPERATURE", PSDouble)
        , ("ALPHA_C", PSDouble)
        , ("ALPHA_E", PSDouble)
        , ("BEAD_DENSITY", PSDouble)
        , ("BEAD_DIAMETER", PSDouble)
        , ("BEAD_EMISSIVITY", PSDouble)
        , ("BEAD_HEAT_TRANSFER_COEFFICIENT", PSDouble)
        , ("BEAD_SPECIFIC_HEAT", PSDouble)
        , ("BETA_C", PSDouble)
        , ("BETA_E", PSDouble)
        -- , ("FED_ACTIVITY", PSString)
        , ("CHARACTERISTIC_VELOCITY", PSDouble)
        , ("C_FACTOR", PSDouble)
        , ("DENSITY", PSDouble)
        , ("DIAMETER", PSDouble)
        , ("EMISSIVITY", PSDouble)
        , ("FLOW_RAMP", PSString)
        , ("FLOW_RATE", PSDouble)
        , ("FLOW_TAU", PSDouble)
        , ("GAUGE_EMISSIVITY", PSDouble)
        , ("GAUGE_TEMPERATURE", PSDouble)
        , ("HEAT_TRANSFER_COEFFICIENT", PSDouble)
        , ("ID", PSString)
        , ("INITIAL_TEMPERATURE", PSDouble)
        , ("K_FACTOR", PSDouble)
        , ("LENGTH", PSDouble)
        , ("MASS_FLOW_RATE", PSDouble)
        , ("OFFSET", PSDouble)
        , ("OPERATING_PRESSURE", PSDouble)
        , ("ORIFICE_DIAMETER", PSDouble)
        , ("P0", PSString)
        , ("PARTICLES_PER_SECOND", PSInt)
        , ("PARTICLE_VELOCITY", PSDouble)
        , ("PART_ID", PSString)
        , ("PDPA_END", PSDouble)
        , ("PDPA_HISTOGRAM", PSBool)
        , ("PDPA_HISTOGRAM_LIMITS", PSArray PSDouble)
        , ("PDPA_HISTOGRAM_NBINS", PSInt)
        , ("PDPA_HISTOGRAM_CUMULATIVE", PSBool)
        , ("PDPA_INTEGRATE", PSBool)
        , ("PDPA_M", PSInt)
        , ("PDPA_N", PSInt)
        , ("PDPA_NORMALIZE", PSBool)
        , ("PDPA_RADIUS", PSDouble)
        , ("PDPA_START", PSDouble)
        , ("PRESSURE_RAMP", PSString)
        -- , ("PX", PSString)
        -- , ("PXX", PSString)
        , ("QUANTITY", PSString)
        , ("RTI", PSDouble)
        , ("SMOKEVIEW_ID", PSArray PSString)
        , ("SMOKEVIEW_PARAMETERS", PSArray PSString)
        , ("SPEC_ID", PSString)
        , ("SPRAY_ANGLE", PSArray PSDouble)
        , ("SPRAY_PATTERN_BETA", PSDouble)
        , ("SPRAY_PATTERN_MU", PSDouble)
        , ("SPRAY_PATTERN_SHAPE", PSString)
        , ("SPRAY_PATTERN_TABLE", PSString)
        , ("VELOCITY_COMPONENT", PSInt)
        -- , ("DROPLET_VELOCITY", PSString)
        ])
    , ("MATL", M.fromList
        [ ("A", PSArray PSDouble)
        , ("ABSORPTION_COEFFICIENT", PSDouble)
        , ("BOILING_TEMPERATURE", PSDouble)
        , ("COLOR", PSString)
        , ("CONDUCTIVITY", PSDouble)
        , ("CONDUCTIVITY_RAMP", PSString)
        , ("DENSITY", PSDouble)
        , ("E", PSArray PSDouble)
        , ("EMISSIVITY", PSDouble)
        , ("FYI", PSString)
        , ("HEATING_RATE", PSArray PSDouble)
        , ("HEAT_OF_COMBUSTION", PSArray PSDouble)
        , ("HEAT_OF_REACTION", PSArray PSDouble)
        , ("ID", PSString)
        , ("MATL_ID", PSArray PSString)
        , ("NU_MATL", PSArray PSDouble)
        , ("NU_SPEC", PSArray PSDouble)
        , ("N_REACTIONS", PSInt)
        , ("N_S", PSArray PSDouble)
        , ("N_T", PSArray PSDouble)
        , ("N_O2", PSArray PSDouble)
        , ("PCR", PSArray PSBool)
        , ("PYROLYSIS_RANGE", PSArray PSDouble)
        , ("REFERENCE_RATE", PSArray PSDouble)
        , ("REFERENCE_TEMPERATURE", PSArray PSDouble)
        , ("RGB", PSArray PSDouble)
        , ("SPECIFIC_HEAT", PSDouble)
        , ("SPECIFIC_HEAT_RAMP", PSString)
        , ("SPEC_ID", PSArray PSString)
        , ("THRESHOLD_SIGN", PSArray PSDouble)
        , ("THRESHOLD_TEMPERATURE", PSArray PSDouble)
        -- , ("POROSITY", PSString)
        , ("ALLOW_SHRINKING", PSBool)
        , ("ALLOW_SWELLING", PSBool)
        , ("GAS_DIFFUSION_DEPTH", PSArray PSDouble)
        ])
    , ("SURF", M.fromList
        [ ("ADIABATIC", PSBool)
        -- , ("AUTO_IGNITION_TEMPERATURE", PSString)
        , ("BACKING", PSString)
        , ("BURN_AWAY", PSBool)
        , ("CELL_SIZE_FACTOR", PSDouble)
        , ("C_FORCED_CONSTANT", PSDouble)
        , ("C_FORCED_PR_EXP", PSDouble)
        , ("C_FORCED_RE", PSDouble)
        , ("C_FORCED_RE_EXP", PSDouble)
        , ("C_HORIZONTAL", PSDouble)
        , ("C_VERTICAL", PSDouble)
        , ("COLOR", PSString)
        , ("CONVECTION_LENGTH_SCALE", PSDouble)
        , ("CONVECTIVE_HEAT_FLUX", PSDouble)
        , ("CONVERT_VOLUME_TO_MASS", PSBool)
        , ("DEFAULT", PSBool)
        , ("DT_INSERT", PSDouble)
        , ("EMISSIVITY", PSDouble)
        , ("EMISSIVITY_BACK", PSDouble)
        , ("EVAC_DEFAULT", PSBool)
        , ("EXTERNAL_FLUX", PSDouble)
        , ("E_COEFFICIENT", PSDouble)
        , ("FIRELINE_MLR_MAX", PSDouble)
        , ("FREE_SLIP", PSBool)
        , ("FYI", PSString)
        , ("GEOMETRY", PSString)
        , ("HEAT_OF_VAPORIZATION", PSDouble)
        , ("HEAT_TRANSFER_COEFFICIENT", PSDouble)
        , ("HEAT_TRANSFER_COEFFICIENT_BACK", PSDouble)
        , ("HEAT_TRANSFER_MODEL", PSString)
        , ("HRRPUA", PSDouble)
        , ("HT3D", PSBool)
        , ("ID", PSString)
        , ("IGNITION_TEMPERATURE", PSDouble)
        , ("INNER_RADIUS", PSDouble)
        , ("INTERNAL_HEAT_SOURCE", PSArray PSDouble)
        , ("LAYER_DIVIDE", PSDouble)
        , ("LEAK_PATH", PSArray PSInt)
        , ("LENGTH", PSDouble)
        , ("MASS_FLUX", PSArray PSDouble)
        , ("MASS_FLUX_TOTAL", PSDouble)
        , ("MASS_FLUX_VAR", PSDouble)
        , ("MASS_FRACTION", PSArray PSDouble)
        , ("MASS_TRANSFER_COEFFICIENT", PSDouble)
        , ("MATL_ID", PSArray PSString)
        , ("MATL_MASS_FRACTION", PSArray PSDouble)
        , ("MINIMUM_LAYER_THICKNESS", PSDouble)
        , ("MLRPUA", PSDouble)
        -- , ("N_CELLS_MAX", PSString)
        , ("N_LAYER_CELLS_MAX", PSArray PSInt)
        , ("NET_HEAT_FLUX", PSDouble)
        , ("NO_SLIP", PSBool)
        , ("NPPC", PSInt)
        , ("PARTICLE_MASS_FLUX", PSDouble)
        , ("PART_ID", PSString)
        , ("PLE", PSDouble)
        , ("PROFILE", PSString)
        , ("RADIUS", PSDouble)
        , ("RAMP_EF", PSString)
        , ("RAMP_MF", PSArray PSString)
        , ("RAMP_PART", PSString)
        , ("RAMP_Q", PSString)
        , ("RAMP_T", PSString)
        , ("RAMP_T_I", PSString)
        , ("RAMP_V", PSString)
        , ("RAMP_V_X", PSString)
        , ("RAMP_V_Y", PSString)
        , ("RAMP_V_Z", PSString)
        , ("RGB", PSArray PSDouble)
        , ("ROUGHNESS", PSDouble)
        , ("SPEC_ID", PSString)
        , ("SPREAD_RATE", PSDouble)
        , ("STRETCH_FACTOR", PSArray PSDouble)
        , ("TAU_EF", PSDouble)
        , ("TAU_MF", PSDouble)
        , ("TAU_PART", PSDouble)
        , ("TAU_Q", PSDouble)
        , ("TAU_T", PSDouble)
        , ("TAU_V", PSDouble)
        , ("TEXTURE_HEIGHT", PSDouble)
        , ("TEXTURE_MAP", PSString)
        , ("TEXTURE_WIDTH", PSDouble)
        , ("TGA_ANALYSIS", PSBool)
        , ("TGA_FINAL_TEMPERATURE", PSDouble)
        , ("TGA_HEATING_RATE", PSDouble)
        , ("THICKNESS", PSArray PSDouble)
        , ("TMP_BACK", PSDouble)
        , ("TMP_FRONT", PSDouble)
        , ("TMP_INNER", PSArray PSDouble)
        , ("TRANSPARENCY", PSDouble)
        , ("VEGETATION", PSBool)
        , ("VEGETATION_ARRHENIUS_DEGRAD", PSBool)
        , ("VEGETATION_CDRAG", PSDouble)
        , ("VEGETATION_CHAR_FRACTION", PSDouble)
        , ("VEGETATION_ELEMENT_DENSITY", PSInt)
        , ("VEGETATION_GROUND_TEMP", PSDouble)
        , ("VEGETATION_HEIGHT", PSDouble)
        , ("VEGETATION_INITIAL_TEMP", PSDouble)
        , ("VEGETATION_LAYERS", PSInt)
        , ("VEGETATION_LINEAR_DEGRAD", PSBool)
        , ("VEGETATION_LOAD", PSDouble)
        , ("VEGETATION_LSET_IGNITE_TIME", PSDouble)
        , ("VEG_LSET_QCON", PSDouble)
        , ("VEGETATION_MOISTURE", PSDouble)
        , ("VEGETATION_NO_BURN", PSBool)
        , ("VEGETATION_SVRATIO", PSInt)
        , ("VEG_LEVEL_SET_SPREAD", PSBool)
        , ("VEG_LSET_ROS_BACK", PSDouble)
        , ("VEG_LSET_ROS_FLANK", PSDouble)
        , ("VEG_LSET_ROS_HEAD", PSDouble)
        , ("VEG_LSET_WIND_EXP", PSDouble)
        , ("VEG_LSET_SIGMA", PSDouble)
        , ("VEG_LSET_HT", PSDouble)
        , ("VEG_LSET_BETA", PSDouble)
        , ("VEG_LSET_ELLIPSE", PSDouble)
        , ("VEG_LSET_TAN2", PSBool)
        , ("VEG_LSET_ELLIPSE_HEAD", PSDouble)
        , ("VEL", PSDouble)
        , ("VEL_BULK", PSDouble)
        , ("VEL_GRAD", PSDouble)
        , ("VEL_T", PSArray PSDouble)
        , ("VOLUME_FLOW", PSDouble)
        , ("WIDTH", PSDouble)
        , ("XYZ", PSArray PSDouble)
        , ("Z0", PSDouble)
        -- , ("ZETA_FRONT", PSString)
        -- , ("EXTERNAL_FLUX_RAMP", PSString)
        -- , ("TAU_EXTERNAL_FLUX", PSString)
        -- , ("VOLUME_FLUX", PSString)
        ])
    , ("PRES", M.fromList
        [ ("CHECK_POISSON", PSBool)
        , ("FISHPAK_BC", PSArray PSInt)
        -- , ("GLMAT_SOLVER", PSString)
        , ("ITERATION_SUSPEND_FACTOR", PSDouble)
        -- , ("LAPLACE_PRESSURE_CORRECTION", PSString)
        , ("MAX_PRESSURE_ITERATIONS", PSInt)
        , ("PRESSURE_RELAX_TIME", PSDouble)
        , ("PRESSURE_TOLERANCE", PSDouble)
        , ("RELAXATION_FACTOR", PSDouble)
        , ("SCARC_METHOD", PSString)
        , ("SCARC_KRYLOV", PSString)
        , ("SCARC_MULTIGRID", PSString)
        , ("SCARC_SMOOTH", PSString)
        , ("SCARC_PRECON", PSString)
        , ("SCARC_COARSE", PSString)
        , ("SCARC_INITIAL", PSString)
        , ("SCARC_ACCURACY", PSDouble)
        , ("SCARC_DEBUG", PSString)
        , ("SCARC_MULTIGRID_CYCLE", PSString)
        , ("SCARC_MULTIGRID_LEVEL", PSString)
        , ("SCARC_MULTIGRID_COARSENING", PSString)
        , ("SCARC_MULTIGRID_ITERATIONS", PSInt)
        , ("SCARC_MULTIGRID_ACCURACY", PSDouble)
        , ("SCARC_MULTIGRID_INTERPOL", PSString)
        , ("SCARC_KRYLOV_ITERATIONS", PSInt)
        , ("SCARC_KRYLOV_ACCURACY", PSDouble)
        , ("SCARC_SMOOTH_ITERATIONS", PSInt)
        , ("SCARC_SMOOTH_ACCURACY", PSDouble)
        , ("SCARC_SMOOTH_OMEGA", PSString)
        , ("SCARC_PRECON_ITERATIONS", PSInt)
        , ("SCARC_PRECON_ACCURACY", PSDouble)
        , ("SCARC_PRECON_OMEGA", PSString)
        , ("SCARC_COARSE_ITERATIONS", PSInt)
        , ("SCARC_COARSE_ACCURACY", PSDouble)
        , ("SOLVER", PSString)
        , ("SUSPEND_PRESSURE_ITERATIONS", PSInt)
        , ("VELOCITY_TOLERANCE", PSDouble)
        ])
    , ("RADI", M.fromList
        [ ("ANGLE_INCREMENT", PSInt)
        , ("BAND_LIMITS", PSArray PSDouble)
        , ("C_MAX", PSDouble)
        , ("C_MIN", PSDouble)
        , ("INITIAL_RADIATION_ITERATIONS", PSInt)
        , ("KAPPA0", PSDouble)
        , ("NMIEANG", PSInt)
        , ("NUMBER_RADIATION_ANGLES", PSInt)
        , ("PATH_LENGTH", PSDouble)
        , ("RADIATION", PSBool)
        , ("RADIATION_ITERATIONS", PSInt)
        -- , ("RADIATIVE_FRACTION", PSString)
        , ("RADTMP", PSDouble)
        -- , ("RTE_SOURCE_CORRECTION", PSString)
        , ("TIME_STEP_INCREMENT", PSInt)
        , ("WIDE_BAND_MODEL", PSBool)
        , ("MIE_MINIMUM_DIAMETER", PSDouble)
        , ("MIE_MAXIMUM_DIAMETER", PSDouble)
        , ("MIE_NDG", PSInt)
        , ("NUMBER_INITIAL_ITERATIONS", PSInt)
        , ("QR_CLIP", PSDouble)
        ])
    , ("CLIP", M.fromList
        [ ("FYI", PSString)
        , ("MAXIMUM_DENSITY", PSDouble)
        , ("MAXIMUM_TEMPERATURE", PSDouble)
        , ("MINIMUM_DENSITY", PSDouble)
        , ("MINIMUM_TEMPERATURE", PSDouble)
        ])
    , ("RAMP", M.fromList
        [ ("CTRL_ID", PSString)
        , ("DEVC_ID", PSString)
        , ("F", PSDouble)
        , ("FYI", PSString)
        , ("ID", PSString)
        , ("NUMBER_INTERPOLATION_POINTS", PSInt)
        , ("T", PSDouble)
        , ("X", PSDouble)
        , ("Z", PSDouble)
        ])
    , ("TABL", M.fromList
        [ ("FYI", PSString)
        , ("ID", PSString)
        , ("TABLE_DATA", PSArray PSDouble)
        ])
    , ("OBST", M.fromList
        [ ("ALLOW_VENT", PSBool)
        , ("BNDF_FACE", PSArray PSBool)
        , ("BNDF_OBST", PSBool)
        , ("BULK_DENSITY", PSDouble)
        , ("COLOR", PSString)
        , ("CTRL_ID", PSString)
        , ("DEVC_ID", PSString)
        , ("EVACUATION", PSBool)
        , ("FYI", PSString)
        , ("HT3D", PSBool)
        , ("ID", PSString)
        , ("MATL_ID", PSString)
        , ("MESH_ID", PSString)
        , ("MULT_ID", PSString)
        , ("NOTERRAIN", PSBool)
        , ("OUTLINE", PSBool)
        , ("OVERLAY", PSBool)
        , ("PERMIT_HOLE", PSBool)
        , ("PROP_ID", PSString)
        , ("REMOVABLE", PSBool)
        , ("RGB", PSArray PSDouble)
        , ("SURF_ID", PSString)
        , ("SURF_ID6", PSArray PSString)
        , ("SURF_IDS", PSArray PSString)
        , ("TEXTURE_ORIGIN", PSArray PSDouble)
        , ("THICKEN", PSBool)
        , ("TRANSPARENCY", PSDouble)
        , ("XB", PSArray PSDouble)
        ])
    , ("HOLE", M.fromList
        [ ("COLOR", PSString)
        , ("CTRL_ID", PSString)
        , ("DEVC_ID", PSString)
        , ("EVACUATION", PSBool)
        , ("FYI", PSString)
        , ("ID", PSString)
        , ("MESH_ID", PSString)
        , ("MULT_ID", PSString)
        , ("RGB", PSArray PSDouble)
        , ("TRANSPARENCY", PSDouble)
        , ("XB", PSArray PSDouble)
        ])
    , ("VENT", M.fromList
        [ ("COLOR", PSString)
        , ("CTRL_ID", PSString)
        , ("DEVC_ID", PSString)
        , ("DYNAMIC_PRESSURE", PSDouble)
        , ("EVACUATION", PSBool)
        , ("FYI", PSString)
        , ("ID", PSString)
        , ("IOR", PSInt)
        , ("L_EDDY", PSDouble)
        , ("L_EDDY_IJ", PSArray PSInt)
        , ("MB", PSString)
        , ("MESH_ID", PSString)
        , ("MULT_ID", PSString)
        , ("N_EDDY", PSInt)
        , ("OUTLINE", PSBool)
        , ("PBX", PSDouble)
        , ("PBY", PSDouble)
        , ("PBZ", PSDouble)
        , ("PRESSURE_RAMP", PSString)
        , ("RADIUS", PSDouble)
        , ("REYNOLDS_STRESS", PSArray PSDouble)
        , ("RGB", PSArray PSDouble)
        , ("SPREAD_RATE", PSDouble)
        , ("SURF_ID", PSString)
        , ("TEXTURE_ORIGIN", PSArray PSDouble)
        , ("TMP_EXTERIOR", PSDouble)
        , ("TMP_EXTERIOR_RAMP", PSString)
        , ("TRANSPARENCY", PSDouble)
        , ("UVW", PSArray PSDouble)
        , ("VEL_RMS", PSDouble)
        -- , ("WIND", PSString)
        , ("XB", PSArray PSDouble)
        , ("XYZ", PSArray PSDouble)
        ])
    , ("INIT", M.fromList
        [ ("AUTO_IGNITION_TEMPERATURE", PSDouble)
        , ("CELL_CENTERED", PSBool)
        , ("CTRL_ID", PSString)
        , ("DENSITY", PSDouble)
        , ("DEVC_ID", PSString)
        , ("DIAMETER", PSDouble)
        , ("DT_INSERT", PSDouble)
        , ("DX", PSDouble)
        , ("DY", PSDouble)
        , ("DZ", PSDouble)
        , ("HEIGHT", PSDouble)
        , ("HRRPUV", PSDouble)
        , ("ID", PSString)
        , ("MASS_FRACTION", PSArray PSDouble)
        , ("MASS_PER_TIME", PSDouble)
        , ("MASS_PER_VOLUME", PSDouble)
        , ("MULT_ID", PSString)
        , ("N_PARTICLES", PSInt)
        , ("N_PARTICLES_PER_CELL", PSInt)
        , ("PART_ID", PSString)
        , ("RADIUS", PSDouble)
        , ("SHAPE", PSString)
        , ("SPEC_ID", PSArray PSString)
        , ("TEMPERATURE", PSDouble)
        , ("UVW", PSArray PSDouble)
        , ("XB", PSArray PSDouble)
        , ("XYZ", PSArray PSDouble)
        , ("PARTICLE_WEIGHT_FACTOR", PSDouble)
        , ("NUMBER_INITIAL_PARTICLES", PSInt)
        ])
    , ("ZONE", M.fromList
        [ ("ID", PSString)
        , ("LEAK_AREA", PSDouble)
        , ("LEAK_PRESSURE_EXPONENT", PSDouble)
        , ("LEAK_REFERENCE_PRESSURE", PSDouble)
        , ("XB", PSArray PSDouble)
        , ("PERIODIC", PSBool)
        ])
    , ("DEVC", M.fromList
        [ ("BYPASS_FLOWRATE", PSDouble)
        , ("CONVERSION_FACTOR", PSDouble)
        , ("COORD_FACTOR", PSDouble)
        , ("CTRL_ID", PSString)
        , ("DELAY", PSDouble)
        , ("DEPTH", PSDouble)
        , ("DEVC_ID", PSString)
        , ("DRY", PSBool)
        , ("DUCT_ID", PSString)
        , ("EVACUATION", PSBool)
        , ("FLOWRATE", PSDouble)
        , ("FYI", PSString)
        -- , ("GHOST_CELL_IOR", PSString)
        , ("HIDE_COORDINATES", PSBool)
        , ("ID", PSString)
        , ("INITIAL_STATE", PSBool)
        , ("INIT_ID", PSString)
        , ("IOR", PSInt)
        , ("LATCH", PSBool)
        , ("MATL_ID", PSString)
        , ("NODE_ID", PSArray PSString)
        , ("NO_UPDATE_DEVC_ID", PSString)
        , ("NO_UPDATE_CTRL_ID", PSString)
        , ("ORIENTATION", PSArray PSDouble)
        , ("ORIENTATION_NUMBER", PSInt)
        , ("OUTPUT", PSBool)
        , ("PART_ID", PSString)
        , ("PIPE_INDEX", PSInt)
        , ("POINTS", PSInt)
        , ("PROP_ID", PSString)
        , ("QUANTITY", PSString)
        , ("QUANTITY2", PSString)
        , ("QUANTITY_RANGE", PSArray PSDouble)
        , ("R_ID", PSString)
        , ("REAC_ID", PSString)
        , ("RELATIVE", PSBool)
        , ("ROTATION", PSDouble)
        , ("SETPOINT", PSDouble)
        , ("SMOOTHING_FACTOR", PSDouble)
        , ("SPEC_ID", PSString)
        , ("STATISTICS", PSString)
        , ("STATISTICS_START", PSDouble)
        , ("SURF_ID", PSString)
        , ("TIME_AVERAGED", PSBool)
        , ("TIME_HISTORY", PSBool)
        , ("TRIP_DIRECTION", PSInt)
        , ("UNITS", PSString)
        , ("VELO_INDEX", PSInt)
        , ("XB", PSArray PSDouble)
        , ("XYZ", PSArray PSDouble)
        , ("X_ID", PSString)
        , ("Y_ID", PSString)
        , ("Z_ID", PSString)
        ])
    , ("CTRL", M.fromList
        [ ("CONSTANT", PSDouble)
        -- , ("CYCLES", PSString)
        -- , ("CYCLE_TIME", PSString)
        , ("DELAY", PSDouble)
        , ("DIFFERENTIAL_GAIN", PSDouble)
        , ("EVACUATION", PSBool)
        , ("FUNCTION_TYPE", PSString)
        , ("ID", PSString)
        , ("INITIAL_STATE", PSBool)
        , ("INTEGRAL_GAIN", PSDouble)
        , ("INPUT_ID", PSArray  PSString)
        , ("LATCH", PSBool)
        , ("N", PSInt)
        , ("ON_BOUND", PSString)
        , ("PROPORTIONAL_GAIN", PSDouble)
        , ("RAMP_ID", PSString)
        , ("SETPOINT", PSDouble)
        , ("TARGET_VALUE", PSDouble)
        , ("TRIP_DIRECTION", PSInt)
        ])
    , ("PROF", M.fromList
        [ ("FORMAT_INDEX", PSInt)
        , ("FYI", PSString)
        , ("ID", PSString)
        , ("IOR", PSInt)
        , ("QUANTITY", PSString)
        , ("XYZ", PSArray PSDouble)
        ])
    , ("ISOF", M.fromList
        [ ("FYI", PSString)
        , ("QUANTITY", PSString)
        , ("SPEC_ID", PSString)
        , ("VALUE", PSArray PSDouble)
        , ("VELO_INDEX", PSInt)
        ])
    , ("SLCF", M.fromList
        [ ("AGL_SLICE", PSString)
        , ("CELL_CENTERED", PSBool)
        , ("EVACUATION", PSBool)
        -- , ("FACE_CENTERED", PSString)
        -- , ("FIRE_LINE", PSString)
        , ("FYI", PSString)
        , ("ID", PSString)
        , ("IOR", PSInt)
        , ("LEVEL_SET_FIRE_LINE", PSString)
        , ("MAXIMUM_VALUE", PSDouble)
        , ("MESH_NUMBER", PSInt)
        , ("MINIMUM_VALUE", PSDouble)
        , ("PART_ID", PSString)
        , ("PBX", PSDouble)
        , ("PBY", PSDouble)
        , ("PBZ", PSDouble)
        -- , ("PROP_ID", PSString)
        , ("QUANTITY", PSString)
        , ("QUANTITY2", PSString)
        , ("REAC_ID", PSString)
        -- , ("SLICETYPE", PSString)
        , ("SPEC_ID", PSString)
        , ("VECTOR", PSBool)
        , ("VELO_INDEX", PSInt)
        , ("XB", PSArray PSDouble)
        ])
    , ("BNDF", M.fromList
        [ ("CELL_CENTERED", PSBool)
        , ("FYI", PSString)
        , ("PART_ID", PSString)
        , ("PROP_ID", PSString)
        , ("QUANTITY", PSString)
        , ("SPEC_ID", PSString)
        , ("STATISTICS", PSString)
        ])
    , ("BNDE", M.fromList
        [ ("CELL_CENTERED", PSString)
        , ("FYI", PSString)
        , ("PART_ID", PSString)
        , ("PROP_ID", PSString)
        , ("QUANTITY", PSString)
        , ("SPEC_ID", PSString)
        ])
    , ("HVAC", M.fromList
        [ ("AIRCOIL_ID", PSString)
        , ("AMBIENT", PSBool)
        , ("AREA", PSDouble)
        , ("CLEAN_LOSS", PSDouble)
        , ("COOLANT_SPECIFIC_HEAT", PSDouble)
        , ("COOLANT_MASS_FLOW", PSDouble)
        , ("COOLANT_TEMPERATURE", PSDouble)
        , ("CTRL_ID", PSString)
        , ("DAMPER", PSBool)
        , ("DEVC_ID", PSString)
        , ("DIAMETER", PSDouble)
        , ("DUCT_ID", PSArray PSString)
        , ("DUCT_INTERP_TYPE", PSString)
        , ("EFFICIENCY", PSArray PSDouble)
        , ("FAN_ID", PSString)
        , ("FILTER_ID", PSString)
        , ("FIXED_Q", PSArray PSDouble)
        , ("ID", PSString)
        , ("LEAK_ENTHALPY", PSBool)
        , ("LENGTH", PSDouble)
        , ("LOADING", PSArray PSDouble)
        , ("LOADING_MULTIPLIER", PSArray PSDouble)
        , ("LOSS", PSArray PSDouble)
        , ("MASS_FLOW", PSDouble)
        , ("MAX_FLOW", PSDouble)
        , ("MAX_PRESSURE", PSDouble)
        , ("N_CELLS", PSInt)
        , ("NODE_ID", PSArray PSString)
        , ("PERIMETER", PSDouble)
        , ("RAMP_ID", PSString)
        , ("RAMP_LOSS", PSString)
        , ("REVERSE", PSBool)
        , ("ROUGHNESS", PSDouble)
        , ("SPEC_ID", PSString)
        , ("TAU_AC", PSDouble)
        , ("TAU_FAN", PSDouble)
        , ("TAU_VF", PSDouble)
        , ("TYPE_ID", PSString)
        , ("VENT_ID", PSString)
        , ("VENT2_ID", PSString)
        , ("VOLUME_FLOW", PSDouble)
        , ("XYZ", PSArray PSDouble)
        ])
    -- , ("GEOM", M.fromList
    --     [ ("AUTO_TEXTURE", PSString)
    --     , ("AZIM", PSString)
    --     , ("AZIM_DOT", PSString)
    --     , ("COMPONENT_ONLY", PSString)
    --     , ("CUTCELLS", PSString)
    --     , ("DAZIM", PSString)
    --     , ("DELEV", PSString)
    --     , ("DSCALE", PSString)
    --     , ("DT_BNDC", PSString)
    --     , ("DT_GEOC", PSString)
    --     , ("DXYZ0", PSString)
    --     , ("DXYZ", PSString)
    --     , ("ELEV", PSString)
    --     , ("ELEV_DOT", PSString)
    --     , ("FACES", PSString)
    --     , ("GAXIS", PSString)
    --     , ("GEOM_IDS", PSString)
    --     , ("GROTATE", PSString)
    --     , ("GROTATE_DOT", PSString)
    --     , ("ID", PSString)
    --     , ("IJK", PSArray PSInt)
    --     , ("MATL_ID", PSString)
    --     , ("N_LAT", PSString)
    --     , ("N_LEVELS", PSString)
    --     , ("N_LONG", PSString)
    --     , ("SCALE", PSString)
    --     , ("SCALE_DOT", PSString)
    --     , ("SPHERE_ORIGIN", PSString)
    --     , ("SPHERE_RADIUS", PSString)
    --     , ("SPHERE_TYPE", PSString)
    --     , ("SURF_ID", PSString)
    --     , ("TEXTURE_MAPPING", PSString)
    --     , ("TEXTURE_ORIGIN", PSString)
    --     , ("TEXTURE_SCALE", PSString)
    --     , ("VERTS", PSString)
    --     , ("VOLUS", PSString)
    --     , ("XB", PSArray PSDouble)
    --     , ("XYZ0", PSString)
    --     , ("XYZ", PSArray PSDouble)
    --     , ("XYZ_DOT", PSString)
    --     , ("ZMIN", PSString)
    --     , ("ZVALS", PSString)
    --     , ("BNDC_FILENAME", PSString)
    --     , ("GEOC_FILENAME", PSString)
    --     ])
    , ("TRNX", M.fromList
        [ ("CC", PSDouble)
        , ("FYI", PSString)
        , ("IDERIV", PSInt)
        , ("MESH_NUMBER", PSInt)
        , ("PC", PSDouble)
        ])
    , ("TRNY", M.fromList
        [ ("CC", PSDouble)
        , ("FYI", PSString)
        , ("IDERIV", PSInt)
        , ("MESH_NUMBER", PSInt)
        , ("PC", PSDouble)
        ])
    , ("TRNZ", M.fromList
        [ ("CC", PSDouble)
        , ("FYI", PSString)
        , ("IDERIV", PSInt)
        , ("MESH_NUMBER", PSInt)
        , ("PC", PSDouble)
        ])
    , ("TAIL", M.empty)
    ]